---
# Store OpenShift cluster credentials in Vault
# This task file handles storing kubeconfig and kubeadmin credentials

- name: "Verify credential files exist"
  ansible.builtin.stat:
    path: "{{ item }}"
  register: credential_files
  loop:
    - "{{ ocp_install_dir }}/auth/kubeconfig"
    - "{{ ocp_install_dir }}/auth/kubeadmin-password"
  tags:
    - vault

- name: "Display credential storage information"
  ansible.builtin.debug:
    msg: |-
      Storing cluster credentials in Vault...
      Cluster: {{ cluster_name }}
      Version: {{ ocp_version }}
      Source directory: {{ ocp_install_dir }}/auth/
      Vault address: {{ vault_addr }}
      
      Files to store:
        {% for file in credential_files.results %}
        - {{ file.item | basename }}: {{ "Found" if file.stat.exists else "Missing" }}
        {% endfor %}
  tags:
    - vault

- name: Add kubeconfig and kubeadmin credentials to Vault
  ansible.builtin.include_role:
    name: proxshift.openshift.vault_credentials
    apply:
      tags:
        - vault
  vars:
    vault_credentials_cluster_name: "{{ cluster_name }}"
    vault_credentials_cluster_api_url: "{{ cluster_api_url }}"
    vault_credentials_ocp_install_dir: "{{ ocp_install_dir }}"
    vault_credentials_vault:
      address: "{{ vault_addr }}"
      token: "{{ vault_token }}"
      path: "{{ vault_path | default('secrets/data/openshift') }}"
  when:
    - ocp_install_dir is defined
    - ((ocp_install_dir + '/auth/kubeconfig') is file or (ocp_install_dir + '/auth/kubeadmin-password') is file)
  tags:
    - vault

- name: "Display credential storage completion"
  ansible.builtin.debug:
    msg: |-
      Credentials stored successfully in Vault!
      Cluster: {{ cluster_name }}
      Version: {{ ocp_version }}
      Stored credentials:
        - kubeconfig: {{ cluster_name }}/kubeconfig
        - kubeadmin password: {{ cluster_name }}/kubeadmin-password
      
      Credentials can now be retrieved by:
        - Other ProxShift operations
        - ACM import process
        - External automation tools
  tags:
    - vault
