---
# Main tasks for iso_copy role
# Dynamically mount SMB/NFS shares and copy ISO files

- name: "Display ISO copy operation details"
  ansible.builtin.debug:
    msg: |-
      Starting ISO copy operation
      Source file: {{ iso_source_file }}
      Destination path: {{ iso_destination_path }}
      Destination filename: {{ iso_dest_filename }}
      Protocol: {{ iso_protocol }}
      Remote host: {{ iso_remote_host }}
      Remote path: {{ iso_remote_path }}
      Mount point: {{ iso_mount_point }}
      
      Copy process:
      - Validating source file and parameters
      - Mounting remote share ({{ iso_protocol }})
      - Copying ISO file to destination
      - Cleaning up mount point
      
      Requirements:
      - Source file must exist and be accessible
      - Remote share must be accessible
      - Sufficient disk space on destination
      - Network connectivity to remote host
  tags:
    - iso_copy
    - info

- name: "Validate ISO source file parameter"
  ansible.builtin.fail:
    msg: "iso_source_file is required"
  when: iso_source_file is not defined or iso_source_file == ''
  tags:
    - iso_copy
    - validation

- name: "Validate ISO destination path parameter"
  ansible.builtin.fail:
    msg: "iso_destination_path is required"
  when: iso_destination_path is not defined or iso_destination_path == ''
  tags:
    - iso_copy
    - validation

- name: "Validate protocol parameter"
  ansible.builtin.fail:
    msg: "Unsupported protocol '{{ iso_protocol }}'. Supported: smb, cifs, nfs, file"
  when: iso_protocol not in ['smb', 'cifs', 'nfs', 'file']
  tags:
    - iso_copy
    - validation

- name: "Validate SMB/CIFS credentials"
  ansible.builtin.fail:
    msg: "iso_mount_user and iso_mount_password are required for SMB/CIFS mounts"
  when: iso_protocol in ['smb', 'cifs'] and (iso_mount_user is not defined or iso_mount_password is not defined)
  no_log: true  # Prevent credential exposure in logs
  tags:
    - iso_copy
    - validation

- name: Check if source ISO file exists
  ansible.builtin.stat:
    path: "{{ iso_source_file }}"
  register: iso_source_stat
  tags:
    - iso_copy
    - validation

- name: Fail if source ISO file does not exist
  ansible.builtin.fail:
    msg: "Source ISO file not found: {{ iso_source_file }}"
  when: not iso_source_stat.stat.exists
  tags:
    - iso_copy
    - validation

- name: Create temporary mount point directory
  ansible.builtin.file:
    path: "{{ iso_mount_point }}"
    state: directory
    mode: '0755'
  when: iso_protocol != 'file'
  tags:
    - iso_copy
    - mount

- name: Mount SMB/CIFS share (macOS)
  ansible.builtin.command:
    cmd: "mount_smbfs -o nobrowse //{{ iso_mount_user }}:{{ iso_mount_password }}@{{ iso_remote_host }}{{ iso_remote_path }} {{ iso_mount_point }}"
  when: 
    - iso_protocol in ['smb', 'cifs']
    - ansible_os_family == 'Darwin'
  register: smb_mount_result_macos
  no_log: true
  tags:
    - iso_copy
    - mount

- name: Mount SMB/CIFS share (Linux)
  ansible.builtin.command:
    cmd: "mount -t cifs //{{ iso_remote_host }}{{ iso_remote_path }} {{ iso_mount_point }} -o username={{ iso_mount_user }},password={{ iso_mount_password }},uid={{ ansible_user_uid }},gid={{ ansible_user_gid }},nodev,nosuid"
  when: 
    - iso_protocol in ['smb', 'cifs']
    - ansible_os_family != 'Darwin'
  register: smb_mount_result_linux
  no_log: true
  tags:
    - iso_copy
    - mount

- name: Mount NFS share (macOS)
  ansible.builtin.command:
    cmd: "mount_nfs -o rw,resvport {{ iso_remote_host }}:{{ iso_remote_path }} {{ iso_mount_point }}"
  when: 
    - iso_protocol == 'nfs'
    - ansible_os_family == 'Darwin'
  register: nfs_mount_result_macos
  tags:
    - iso_copy
    - mount

- name: Mount NFS share (Linux)
  ansible.builtin.command:
    cmd: "mount -t nfs {{ iso_remote_host }}:{{ iso_remote_path }} {{ iso_mount_point }} -o rw,sync,nodev,nosuid"
  when: 
    - iso_protocol == 'nfs'
    - ansible_os_family != 'Darwin'
  register: nfs_mount_result_linux
  tags:
    - iso_copy
    - mount

- name: Set destination directory for file protocol
  ansible.builtin.set_fact:
    iso_copy_destination_dir: "{{ iso_destination_path }}"
  when: iso_protocol == 'file'
  tags:
    - iso_copy
    - copy

- name: Set destination directory for network protocols
  ansible.builtin.set_fact:
    iso_copy_destination_dir: "{{ iso_mount_point }}"
  when: iso_protocol != 'file'
  tags:
    - iso_copy
    - copy

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: "{{ iso_copy_destination_dir }}"
    state: directory
    mode: '0755'
  when: iso_protocol == 'file'
  tags:
    - iso_copy
    - copy

- name: Copy ISO file to destination
  ansible.builtin.copy:
    src: "{{ iso_source_file }}"
    dest: "{{ iso_copy_destination_dir }}/{{ iso_dest_filename }}"
    mode: "{{ iso_file_mode }}"
    remote_src: true
  register: iso_copy_result
  tags:
    - iso_copy
    - copy

- name: "Display ISO copy completion status"
  ansible.builtin.debug:
    msg: |-
      ISO copy completed successfully!
      Source file: {{ iso_source_file }}
      Destination: {{ iso_copy_destination_dir }}/{{ iso_dest_filename }}
      Protocol: {{ iso_protocol }}
      Remote host: {{ iso_remote_host }}
      Remote path: {{ iso_remote_path }}
      {% if iso_protocol != 'file' %}Mount point: {{ iso_mount_point }}{% endif %}
      
      Copy details:
      - File size: {{ iso_copy_result.changed | ternary('Copied', 'Already exists') }}
      - Destination accessible: Yes
      - PVE hosts can now access the ISO
      
      Next steps:
      - ISO is ready for PVE VM configuration
      - Continue with VM creation and startup
  when: iso_copy_result is succeeded
  tags:
    - iso_copy
    - copy

# Cleanup block - always runs to ensure mounts are cleaned up
- name: Cleanup mount points
  block:
    - name: Unmount SMB/CIFS share
      ansible.builtin.command:
        cmd: "umount {{ iso_mount_point }}"
      when: 
        - iso_protocol in ['smb', 'cifs'] 
        - (smb_mount_result_macos is defined and smb_mount_result_macos is succeeded) or (smb_mount_result_linux is defined and smb_mount_result_linux is succeeded)
      ignore_errors: true
      no_log: true  # Consistent with mount operation security

    - name: Unmount NFS share
      ansible.builtin.command:
        cmd: "umount {{ iso_mount_point }}"
      when: 
        - iso_protocol == 'nfs'
        - (nfs_mount_result_macos is defined and nfs_mount_result_macos is succeeded) or (nfs_mount_result_linux is defined and nfs_mount_result_linux is succeeded)
      ignore_errors: true

    - name: Remove temporary mount point
      ansible.builtin.file:
        path: "{{ iso_mount_point }}"
        state: absent
      when: iso_protocol != 'file'
      ignore_errors: true

  when: iso_protocol != 'file'
  tags:
    - iso_copy
    - cleanup
