# GitHub Pages Configuration for ProxShift
# Theme: Midnight (GitHub supported theme)

title: ProxShift
description: OpenShift clusters on Proxmox made simple
url: https://randyoyarzabal.github.io
baseurl: /proxshift

# Theme configuration
theme: jekyll-theme-midnight

# Site settings
# logo: /proxshift/assets/images/logo.png
# favicon: /proxshift/assets/images/favicon.ico

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/randyoyarzabal/proxshift

# Footer
footer_content: "ProxShift - Where Proxmox meets OpenShift"

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "//github.com/randyoyarzabal/proxshift"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/