namespace: proxshift
name: hashi_vault
version: 1.0.0
readme: README.md
authors:
  - Randy Oyarzabal <randyoyarzabal@gmail.com>
description: ProxShift HashiCorp Vault integration collection
license:
  - MIT
license_file: ''
tags:
  - vault
  - hashicorp
  - secrets
  - security
  - automation
dependencies: {}
repository: https://github.com/randyoyarzabal/proxshift
documentation: https://github.com/randyoyarzabal/proxshift/tree/main/docs
homepage: https://github.com/randyoyarzabal/proxshift
issues: https://github.com/randyoyarzabal/proxshift/issues
build_ignore: []
